### ISSUE TITLE
Shortcodes not working in latest Event Tickets Plus

### ISSUE THREAD

**Issue by christianarielli** [mt-support/tribe-ext-tickets-additional-fields#1]
I have tried to use the extension with Event Tickets Plus Version 5.1.1 and The Events Calendar PRO 5.2.1.2 on Wordpress 5.6. All shortcodes from the core extensions are working, but shortcodes like [tribe_tickets_additional_field] from this extension do not work.

There are no error messages, the shortcodes are just rendered as pure text.

**Comment by juanfra** [comment]
Hi Christian,

Thank you very much for your report! I hope you had a great start of 2021 🎉 

I just opened a PR and we'll try to get this version out as soon as possible. 

Best,
Juan.

**Comment by juanfra** [comment]
Hi @christianjunk,

Thank you for your patience. We just released an update for this extension that will play nicely with the shortcodes from Event Tickets Plus.

[You can download it here](https://theeventscalendar.com/extensions/additional-fields-for-tickets/).

Have a nice day,
Juan.

**Comment by christianarielli** [comment]
> Hi @christianjunk,
> 
> Thank you for your patience. We just released an update for this extension that will play nicely with the shortcodes from Event Tickets Plus.
> 
> [You can download it here](https://theeventscalendar.com/extensions/additional-fields-for-tickets/).
> 
> Have a nice day,
> Juan.

Thank you very much!!!
